### ISSUE TITLE
Nice plugin

### ISSUE THREAD

**Issue by Hedva** [nagix/chartjs-plugin-style#1]
Nice plugin you've made for ChartJS!

Thanks!

Just one note:
https://nagix.github.io/chartjs-plugin-style/

The first items doesn't appear until you scroll. So the page looks empty when you land on it.
Maybe it's better to make the first item always visible.

Thanks for your work!

**Comment by nagix** [comment]
Thank you for trying the plugin and your comment. I just disabled lazy loading in the tutorial with d368ddb.
