### ISSUE TITLE
Issue: me.calculateCircumference is not a function at ChartElement.updateElement

### ISSUE THREAD

**Issue by jrvaja** [nagix/chartjs-plugin-style#3]
Hey @nagix 

I just got this error. This comes only with polarArea.
![screenshot 2018-11-10 21 10 18](https://user-images.githubusercontent.com/1858318/48303176-0b428d00-e52d-11e8-9cb3-ee3baa161127.png)
 Please have a look.

**Comment by nagix** [comment]
Thank you for reporting the issue. This is caused by incompatibility with Chart.js 2.7.3, and d60001d fixed it.
