### ISSUE TITLE
horizontalBar chart shadows not working

### ISSUE THREAD

**Issue by Screez** [nagix/chartjs-plugin-style#4]
Hi. 
A small question: will you fix an issue with horizontalBar chart type?
![image](https://user-images.githubusercontent.com/26300371/49496822-87e83300-f86f-11e8-8a5d-920306822e41.png)

As you can see: legend contains shadows, but bars - no.(((

**Comment by nagix** [comment]
Thank you for reporting this issue. This is fixed by bf997ab.
